# Generated by Django 3.0.4 on 2020-03-12 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, default='/dress.png', null=True, upload_to='')),
                ('puede_ser_vendido', models.BooleanField(default=False)),
                ('puede_ser_comprado', models.BooleanField(default=False)),
                ('precio_venta', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('precio_coste', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('iva_cobrar', models.FloatField(default=21.0, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('iva_pagar', models.FloatField(default=21.0, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('cantidad_disponible', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
