# Generated by Django 3.0.4 on 2020-03-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
        ('Inventario', '0002_auto_20200312_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Compras.Proveedor'),
        ),
    ]
