# Generated by Django 3.0.4 on 2020-03-13 12:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20200312_1130'),
        ('Ventas', '0003_auto_20200313_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='productos',
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.Producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='Ventas.LineaPedido', to='Inventario.Producto'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
