# Generated by Django 3.0.4 on 2020-03-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_auto_20200313_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Imagen',
            new_name='imagen',
        ),
    ]
