# Generated by Django 3.0.4 on 2020-03-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0006_empleado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contraseña',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_usuario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
