# Generated by Django 3.0.4 on 2020-04-18 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0007_auto_20200322_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nacionalidad',
        ),
        migrations.AddField(
            model_name='empleado',
            name='contrasenya',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empleados.Departamento'),
        ),
    ]
