# Generated by Django 3.0.4 on 2020-04-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0008_auto_20200419_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='contrasenya',
            new_name='contraseña',
        ),
    ]
