# Generated by Django 3.0.4 on 2020-04-29 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0010_empleado_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='coste_partes_horas',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='horas_semanales',
        ),
    ]
