# Generated by Django 3.0.4 on 2020-04-29 01:12

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0011_auto_20200429_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='otra_informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre_usuario',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
