# Generated by Django 3.0.4 on 2020-04-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0012_auto_20200429_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True),
        ),
    ]
