# Generated by Django 3.0.4 on 2020-03-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineacompra',
            old_name='pedido',
            new_name='compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Compras.Proveedor'),
        ),
    ]
